(defun vk-translate-pattern (type)
  (interactive "sEnter Type: ")
  (beginning-of-line)
  (let* ((case-fold-search nil)
         (end (line-end-position)))
    (search-forward "pattern " end)
    (search-forward "VK_" end)
    (search-forward type end)
    (search-forward "_" end))
  (let* ((typec (s-upper-camel-case type))
         (enum (buffer-substring (point) (end-of-thing 'symbol)))
         (enumc (s-upper-camel-case enum)))
    (kill-whole-line)
    (insert "pattern " enumc " = Enumerator VK_" type "_" enum " :: " typec "\n")))

(defun vk-translate-patterns (start end type)
  (interactive "r
sEnter Type: ")
  (goto-char start)
  (let* ((input (buffer-substring start end))
         (output
          (with-temp-buffer
            (insert input)
            (goto-char (point-min))
            (while (< (point) (buffer-end 1))
              (vk-translate-pattern type))
            (buffer-string))))
    (goto-char start)
    (delete-region start end)
    (insert output)))
