flags: {}
packages:
- '.'
- sdl2-vulkan
- location: vulkan
  extra-dep: true
- location:
    git: https://github.com/haskell-game/sdl2.git
    commit: c2c10ea3dbf34aa5c4e50186dbad313e11e00b0f
  extra-dep: true
extra-deps:
- StateVar-1.1.0.4
- adjunctions-4.3
- base-orphans-0.5.4
- bifunctors-5.4.1
- bytes-0.15.2
- cereal-0.5.3.0
- comonad-5
- contravariant-1.4
- distributive-0.5.0.2
- exceptions-0.8.3
- free-4.12.4
- hashable-1.2.4.0
- kan-extensions-5.0.1
- lens-4.14
- linear-1.20.5
- parallel-3.2.1.0
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- reflection-2.1.2
- scientific-0.3.4.9
- semigroupoids-5.1
- semigroups-0.18.2
- stm-2.4.4.1
- tagged-0.8.5
- text-1.2.2.1
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.1
- vector-0.11.0.0
- vector-sized-0.3.2.0
- void-0.7.1
resolver: ghc-8.0.1
